name: Supabase Storage Cleanup

on:
#  schedule:
#    - cron: '*/5 * * * *'  # 매 5분마다 실행
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t cleanup:latest ./supabase-cleanup

      - name: Run Supabase Cleanup
        run: | 
          docker run --rm \
            --env SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            --env SUPABASE_SERVICE_KEY=${{ secrets.SUPABASE_SERVICE_KEY }} \
            cleanup:latest
