name: Supabase Storage Cleanup

on:
  schedule:
    - cron: '*/5 * * * *'  # 매 5분마다 실행

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t supabase-cleanup ./supabase-cleanup

      - name: Run Supabase Cleanup
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: docker run --rm \
          -e SUPABASE_URL=$SUPABASE_URL \
          -e SUPABASE_SERVICE_KEY=$SUPABASE_SERVICE_KEY \
          supabase-cleanup
